# Generated by Django 3.2.12 on 2024-03-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VIN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('equipment_code', models.CharField(max_length=3)),
                ('year_of_issue', models.IntegerField()),
                ('serial_number', models.CharField(max_length=7)),
                ('place_of_production', models.CharField(max_length=2)),
            ],
        ),
    ]
